### PR TITLE
Implement deleting surveys

### LINKED ISSUE #39: Add Delete Survey Feature

### PR DESCRIPTION
**Pull request by AriSengupta**
Description:
- Added ability to delete surveys on the mySurveys page

Test:
- Added JPA and controller tests for deleting surveys

Closes #39

### CODE REVIEW

**Review by thomas7carriere — COMMENTED** [review]
Looking good, just curious about the deleteSurveyWithAuthorization() test. It seems
you're sending a POST to /survey/create, then sending a GET to /survey/list? Just trying to understand what's supposed to be happening.

**Comment by AriSengupta** [comment]
> Looking good, just curious about the deleteSurveyWithAuthorization() test. It seems
> you're sending a POST to /survey/create, then sending a GET to /survey/list? Just trying to understand what's supposed to be happening.

Since the order of tests is arbitrary the delete tests must not affect the other tests in the file. 

The way to solve this is to add a survey (the POST request). Then get how many surveys were added (the GET request). Then delete the last survey that was added (the DELETE request). The number of surveys should be the same before entering deleteSurveyWithAuthorization and after leaving deleteSurveyWithAuthorization.

This method solves the following two cases:

1. A test was run that already added a survey then the deleteSurveyWithAuthorization test will delete survey with an id of 2

2. deleteSurveyWithAuthorization test runs before a survey was added then the test will delete survey with id of 1

Hopefully the explanation makes sense.

**Comment by thomas7carriere** [comment]
The test aren't actually run in an arbitrary order, there is an annotation if you look at the tests in TestSurveyController, @Order(). It also doesn't seem to run a testCase where a DELETE request to /survey/delete/{surveyId} actually works

**Comment by AriSengupta** [comment]
> The test aren't actually run in an arbitrary order, there is an annotation if you look at the tests in TestSurveyController, @order(). It also doesn't seem to run a testCase where a DELETE request to /survey/delete/{surveyId} actually works

The Order annotation is a JUnit 5 feature while in our dependencies we are using JUnit 4. Mixing JUnit versions is not the best idea since on my local machine the Order annotations do not work. 

The deleteSurveyWithAuthorization test has two delete requests. Once the delete is successful (a  HTTP 204 is returned) the second time the delete request is run it fails since the same survey cannot be deleted twice (a HTTP 404 is returned).

**Comment by thomas7carriere** [comment]
Ah sorry, I misinterpreted the status "No Content" as a failure. Not sure where the JUnit.Jupiter is coming from then, if not included somewhere in the Spring framework. Is it not recognized on your machine?

**Review by thomas7carriere — APPROVED** [review]

**Comment by AriSengupta** [comment]
> Ah sorry, I misinterpreted the status "No Content" as a failure. Not sure where the JUnit.Jupiter is coming from then, if not included somewhere in the Spring framework. Is it not recognized on your machine?

It appears junit-jupiter is added by the spring-boot-starter-test dependency.
 
I still think adding a survey then deleting the survey is a good idea to make the test deterministic and not affect other tests. I could change the test to use the order annotation or keep it how it is. What do you think?

**Comment by thomas7carriere** [comment]
> > Ah sorry, I misinterpreted the status "No Content" as a failure. Not sure where the JUnit.Jupiter is coming from then, if not included somewhere in the Spring framework. Is it not recognized on your machine?
> 
> It appears junit-jupiter is added by the spring-boot-starter-test dependency.
> 
> I still think adding a survey then deleting the survey is a good idea to make the test deterministic and not affect other tests. I could change the test to use the order annotation or keep it how it is. What do you think?

While I dont think it was necessarily good design having tests that rely on each other, it gave a way to have each test only use one endpoint. Either way seems fine though if things are passing

**Review by cyang030 — APPROVED** [review]

**Pull request merged**
