### PR TITLE
Implement TextQuestion class

### LINKED ISSUE #2: OpenEndedQuestion Class
Create OpenEndedQuestion Class, use H2 JPA for now.

### PR DESCRIPTION
**Pull request by cyang030**
- Also added jacoco for UT coverage report, which will be available under target/site/jacoco/ after "mvn test"
- Add travis-ci badge into README.md
- Enable all recommended and options/path warnings on compiler

closes #2

### CODE REVIEW

**Comment by cyang030** [comment]
note that I keep the class name as the existing "TextQuestion" instead of the "OpenEndedQuestion".
which name should be used?

**Review by thomas7carriere — COMMENTED** [review]
Looks good to me. Feel free to name the question whatever you think would be best.

**Review by Dom123k — CHANGES_REQUESTED** [review]
Looks good, nice comments to make it clear what's going on.

I think it would be best to label it open ended question as you said to make it more clear.

**Review by thomas7carriere — APPROVED** [review]
Put comment instead of approve by accident.

**Review by thomas7carriere — CHANGES_REQUESTED** [review]
Should probably have a getter and setter for the "string question" field in Question.class

**Review by Dom123k — APPROVED** [review]

**Comment by cyang030** [comment]
> Should probably have a getter and setter for the "string question" field in Question.class

getter/setter added

**Review by thomas7carriere — APPROVED** [review]

**Pull request merged**
