### PR TITLE
Implemented SurveyClass and Tests, issue #12

### PR DESCRIPTION
**Pull request by MikeEvans6**
Also added super class call in default constructor of MultipleChoiceQuestion and OpenEndedQuestion

### CODE REVIEW

**Review by thomas7carriere — CHANGES_REQUESTED** [review]
Looks good, just going to want some persistence tests I think

**Review by cyang030 — COMMENTED** [review]
Some persistence test would be good

**Comment by MikeEvans6** [comment]
> Looks good, just going to want some persistence tests I think

Added the tests

**Review by cyang030 — APPROVED** [review]

**Review by thomas7carriere — APPROVED** [review]

**Comment by thomas7carriere** [comment]
Merging Survey pull request

**Pull request merged**
